server:
  port: 8073

spring:
  application:
    name: gmall-cache-service
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://188.131.254.195/gmall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
  redis:
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 188.131.254.195:26379,188.131.254.195:26380,188.131.254.195:26381
    timeout: 50000

mybatis:
  type-aliases-package: com.tucker.gmall
  mapper-locations: classpath:mapper/*Mapper.xml

mapper:
  identity: MYSQL

manage:
  service:
    version: 1.0.0

dubbo:
  application:
    id: gmall-cache-service
    name: gmall-cache-service
  scan:
    base-packages: com.tucker.gmall
  protocol:
    id: dubbo
    name: dubbo
    port: 12347
    status: server
    serialization: kryo
  registry:
    id: zookepper
    address: zookeeper://188.131.254.195:2183?backup=188.131.254.195:2181,188.131.254.195:2182
    timeout: 600000
    check: false
  provider:
    loadbalance: roundrobin
  config-center:
    address: zookeeper://188.131.254.195:2183?backup=188.131.254.195:2181,188.131.254.195:2182
  metadata-report:
    address: zookeeper://188.131.254.195:2183?backup=188.131.254.195:2181,188.131.254.195:2182

