server:
  port: 8082
spring:
  application:
    name: gmall-item-web
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
manage:
  service:
    version: 1.0.0
dubbo:
  consumer:
    check: false
    timeout: 600000
  scan:
    base-packages: com.tucker.gmall
  application:
    id: gmall-item-web
    name: gmall-item-web

  protocol:
    id: dubbo
    name: dubbo
    port: 12346
    serialization: kryo
  registry:
    id: zookepper
    address: zookeeper://188.131.254.195:2181
    timeout: 600000
  provider:
    loadbalance: roundrobin

mapper:
  identity: MYSQL

logging:
  level:
    com.tucker.gmall: info
