server:
  port: 8080
spring:
  application:
    name: gmall-user-web
user:
  service:
    version: 1.0.0
dubbo:
  application:
    id: gmall-user-web
    name: gmall-user-web
    scan:
      base-packages: com.tucker.gmall
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    serialization: kryo
  registry:
    id: zookepper
    address: zookeeper://188.131.254.195:2181
  provider:
    loadbalance: roundrobin

mapper:
  identity: MYSQL